### ISSUE TITLE
ClassCastException: ForegroundRelativeLayout cannot be cast to PageLayout

### ISSUE THREAD

**Issue by nilsi** [acbelter/DirectionalCarousel#2]
I brought your code into a test project but getting this error

```
java.lang.ClassCastException: com.example.macbookpro.test4.fglayout.ForegroundRelativeLayout cannot be cast to com.example.macbookpro.test4.page.PageLayout
            at com.example.macbookpro.test4.CarouselPagerAdapter.getPageView(CarouselPagerAdapter.java:212)
            at com.example.macbookpro.test4.CarouselPagerAdapter.onPageScrolled(CarouselPagerAdapter.java:117)
```

At this method :

```
    private PageLayout getPageView(int position) {
        String tag = mConfig.getPageFragmentTag(position);
        Fragment f = mFragmentManager.findFragmentByTag(tag);
        if (f != null && f.getView() != null) {
            return (PageLayout) ((ViewGroup) f.getView()).getChildAt(0); // <---- here!
        }
        return null;
    }
```

Any idea what Im doing wrong?

**Comment by acbelter** [comment]
Try return (PageLayout) f.getView()

**Comment by nilsi** [comment]
Ah yeah, I just changed to that and it works. Thank you!
